$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  seed:
    type: string
  taxid:
    type: string
  perso_database:
    type: string
  project_name:
    type: string
  output_folder:
    type: string

  default_psiblast_option:
    type: object
    properties:
      psiblast_e_val:
        type: number
        minimum: 0
        maximum: 1        
      iteration:
        type: number
        minimum: 1
        maximum: 5
      
  default_blast_option:
    type: object
    properties:
      e_val:
        type: number
        minimum: 0
        maximum: 1
      pid:
        type: number
        minimum: 0
        maximum: 1        
      cov:
        type: number
        minimum: 0
        maximum: 1
    required:
      - e_val
      - pid
      - cov

  update_db:
    type: boolean

  ndg_option:
    type: object
    properties:
      section:
        type: string
        enum: ["refseq","genbank"]
      assembly_levels:
        type: string
        enum: ["all", "complete", "chromosome", "scaffold", "contig"]
      refseq_categories:
        type: string
        enum: ["reference", "all"]
      groups:
        type: string
        enum: ["all", "archaea", "bacteria", "fungi", "invertebrate", "metagenomes", "plant", "protozoa", "vertebrate_mammalian", "vertebrate_other", "viral"]
    required:
      - section
      - assembly_levels
      - refseq_categories

  speedup:
    type: boolean

  default_values_plot:
    type: object
    properties:
      color: 
        type: string
      colored_border:
        type: boolean
      round_border:
        type: boolean
        
  PAtab_table:
    type: string

required:
  - seed
  - taxid
  - project_name
  - output_folder
  - default_psiblast_option
  - default_blast_option
  - ndg_option
  - speedup
  - default_values_plot